global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
